name: CI for Performance Dashboard

on:
  push:
    branches: [ "master" ]    # Runs when you push code to main
  pull_request:
    branches: [ "master" ]    # Runs when you make a Pull Request to main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install flask
        pip install psutil

    - name: Run dashboard script
    - name: Creating Docker container
      run: docker build -t monitoring_dashboard
